// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbmodel

var TableNames = struct {
	Alerts            string
	Candidates        string
	ChatConversations string
	ChatMessages      string
	JobApplications   string
	Jobs              string
	UploadFiles       string
	Users             string
}{
	Alerts:            "alerts",
	Candidates:        "candidates",
	ChatConversations: "chat_conversations",
	ChatMessages:      "chat_messages",
	JobApplications:   "job_applications",
	Jobs:              "jobs",
	UploadFiles:       "upload_files",
	Users:             "users",
}
